create table if not exists strategies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  symbol text not null check (symbol in ('TQQQ', 'SOXL', 'RAM')),
  split_count integer not null check (split_count in (20, 40)),
  principal numeric(18, 4) not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null default 0,
  avg_price numeric(18, 4) not null default 0,
  t_value numeric(18, 10) not null default 0,
  mode text not null check (mode in ('normal', 'reverse')) default 'normal',
  reverse_started_at date,
  reverse_first_sell_done boolean not null default false,
  compounding_type text not null check (compounding_type in ('simple', 'compound')) default 'compound',
  is_archived boolean not null default false,
  sort_order integer not null default 0,
  started_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists daily_prices (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  trade_date date not null,
  close_price numeric(18, 4) not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, trade_date)
);

create table if not exists market_candles (
  id bigint generated by default as identity primary key,
  symbol text not null check (symbol = 'SOXL'),
  trade_date date not null,
  open_price numeric(18, 4) not null,
  high_price numeric(18, 4) not null,
  low_price numeric(18, 4) not null,
  close_price numeric(18, 4) not null,
  adjusted_close numeric(18, 4),
  volume bigint not null default 0,
  fetched_at timestamptz not null default now(),
  unique(symbol, trade_date)
);

create table if not exists trade_plans (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  plan_date date not null,
  mode text not null check (mode in ('normal', 'reverse')),
  phase text,
  t_value numeric(18, 10) not null,
  avg_price numeric(18, 4) not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null,
  star_percent numeric(18, 8),
  star_price numeric(18, 4),
  one_unit_budget numeric(18, 4),
  reverse_reference_price numeric(18, 4),
  guidance jsonb not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, plan_date)
);

create table if not exists executions (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  trade_plan_id uuid references trade_plans(id) on delete set null,
  round_id uuid,
  executed_at date not null,
  side text not null check (side in ('buy', 'sell')),
  order_type text not null check (order_type in ('LOC', 'MOC', 'LIMIT', 'MANUAL')),
  quantity integer not null check (quantity > 0),
  avg_execution_price numeric(18, 4) not null,
  total_amount numeric(18, 4) not null,
  t_effect text check (t_effect in ('buy_full', 'buy_half', 'quarter_sell', 'full_sell', 'limit_sell_then_full_buy', 'limit_sell_then_half_buy', 'reverse_buy', 'reverse_sell', 'none')),
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists completed_rounds (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  round_number integer not null,
  symbol text not null check (symbol in ('TQQQ', 'SOXL', 'RAM')),
  split_count integer not null check (split_count in (20, 40)),
  started_at date not null,
  ended_at date not null,
  started_principal numeric(18, 4) not null,
  ending_cash_balance numeric(18, 4) not null,
  profit_amount numeric(18, 4) not null,
  profit_rate numeric(18, 8) not null,
  execution_count integer not null,
  buy_count integer not null,
  sell_count integer not null,
  total_buy_amount numeric(18, 4) not null,
  total_sell_amount numeric(18, 4) not null,
  ending_t_value numeric(18, 10) not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, round_number)
);

alter table strategies drop constraint if exists strategies_symbol_check;
alter table strategies add constraint strategies_symbol_check check (symbol in ('TQQQ', 'SOXL', 'RAM'));

alter table executions drop constraint if exists executions_t_effect_check;
alter table executions add constraint executions_t_effect_check check (t_effect in ('buy_full', 'buy_half', 'quarter_sell', 'full_sell', 'limit_sell_then_full_buy', 'limit_sell_then_half_buy', 'reverse_buy', 'reverse_sell', 'none'));

alter table executions add column if not exists round_id uuid;
do $$
begin
  alter table executions
    add constraint executions_round_id_fkey
    foreign key (round_id) references completed_rounds(id) on delete set null;
exception
  when duplicate_object then null;
end $$;

create table if not exists strategy_snapshots (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  execution_id uuid,
  snapshot_date date not null,
  principal numeric(18, 4),
  mode text not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null,
  avg_price numeric(18, 4) not null,
  t_value numeric(18, 10) not null,
  started_at date,
  reverse_started_at date,
  reverse_first_sell_done boolean,
  note text,
  created_at timestamptz not null default now()
);

alter table strategy_snapshots add column if not exists execution_id uuid;
alter table strategy_snapshots add column if not exists principal numeric(18, 4);
alter table strategy_snapshots add column if not exists started_at date;
alter table strategy_snapshots add column if not exists reverse_started_at date;
alter table strategy_snapshots add column if not exists reverse_first_sell_done boolean;

create unique index if not exists idx_snapshots_execution on strategy_snapshots (execution_id) where execution_id is not null;

create or replace function cancel_latest_execution(p_strategy_id uuid, p_execution_id uuid)
returns void
language plpgsql
set search_path = public
as $$
declare
  v_strategy strategies%rowtype;
  v_execution executions%rowtype;
  v_latest_execution_id uuid;
  v_snapshot strategy_snapshots%rowtype;
  v_round completed_rounds%rowtype;
begin
  select * into v_strategy
  from strategies
  where id = p_strategy_id
  for update;

  if not found then
    raise exception '전략을 찾을 수 없습니다.';
  end if;

  select id into v_latest_execution_id
  from executions
  where strategy_id = p_strategy_id
  order by created_at desc, id desc
  limit 1;

  if v_latest_execution_id is null or v_latest_execution_id <> p_execution_id then
    raise exception '가장 최근에 입력한 체결만 취소할 수 있습니다.';
  end if;

  select * into v_execution
  from executions
  where id = p_execution_id and strategy_id = p_strategy_id
  for update;

  select * into v_snapshot
  from strategy_snapshots
  where execution_id = p_execution_id
  limit 1;

  if not found then
    select * into v_snapshot
    from strategy_snapshots
    where strategy_id = p_strategy_id
      and created_at <= v_execution.created_at
    order by created_at desc, id desc
    limit 1;
  end if;

  if v_snapshot.id is null
     or v_execution.created_at - v_snapshot.created_at > interval '5 minutes' then
    raise exception '체결 직전 상태를 찾을 수 없어 안전하게 취소할 수 없습니다.';
  end if;

  if v_snapshot.mode = 'reverse'
     and v_snapshot.reverse_started_at is null
     and v_strategy.reverse_started_at is null then
    raise exception '기존 리버스 상태의 시작일을 확인할 수 없어 안전하게 자동 취소할 수 없습니다.';
  end if;

  if v_execution.round_id is not null then
    select * into v_round
    from completed_rounds
    where id = v_execution.round_id and strategy_id = p_strategy_id
    for update;

    if not found
       or v_execution.side <> 'sell'
       or v_round.ended_at <> v_execution.executed_at then
      raise exception '라운드 종료 체결 상태를 확인할 수 없습니다.';
    end if;

    delete from completed_rounds where id = v_round.id;
  end if;

  delete from executions where id = v_execution.id;

  update strategies
  set
    principal = coalesce(v_snapshot.principal, v_round.started_principal, v_strategy.principal),
    cash_balance = v_snapshot.cash_balance,
    position_qty = v_snapshot.position_qty,
    avg_price = v_snapshot.avg_price,
    t_value = v_snapshot.t_value,
    mode = v_snapshot.mode,
    reverse_started_at = case
      when v_snapshot.mode = 'normal' then null
      else coalesce(v_snapshot.reverse_started_at, v_strategy.reverse_started_at)
    end,
    reverse_first_sell_done = case
      when v_snapshot.mode = 'normal' then false
      else coalesce(
        v_snapshot.reverse_first_sell_done,
        exists (
          select 1 from executions
          where strategy_id = p_strategy_id
            and round_id is null
            and t_effect = 'reverse_sell'
        )
      )
    end,
    started_at = coalesce(v_snapshot.started_at, v_round.started_at, v_strategy.started_at),
    updated_at = now()
  where id = p_strategy_id;

  delete from strategy_snapshots where id = v_snapshot.id;
end;
$$;

revoke all on function cancel_latest_execution(uuid, uuid) from public;
grant execute on function cancel_latest_execution(uuid, uuid) to service_role;

create index if not exists idx_strategies_active on strategies (is_archived, sort_order, created_at);
create index if not exists idx_daily_prices_strategy_date on daily_prices (strategy_id, trade_date desc);
create index if not exists idx_market_candles_symbol_date on market_candles (symbol, trade_date desc);
create index if not exists idx_trade_plans_strategy_date on trade_plans (strategy_id, plan_date desc);
create index if not exists idx_executions_strategy_date on executions (strategy_id, executed_at desc);
create index if not exists idx_executions_round on executions (round_id, executed_at desc);
create index if not exists idx_snapshots_strategy_date on strategy_snapshots (strategy_id, snapshot_date desc);
create index if not exists idx_completed_rounds_strategy on completed_rounds (strategy_id, round_number desc);

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

alter default privileges in schema public grant all privileges on tables to service_role;
alter default privileges in schema public grant all privileges on sequences to service_role;

notify pgrst, 'reload schema';
