create table if not exists strategies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  symbol text not null check (symbol in ('TQQQ', 'SOXL')),
  split_count integer not null check (split_count in (20, 40)),
  principal numeric(18, 4) not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null default 0,
  avg_price numeric(18, 4) not null default 0,
  t_value numeric(18, 10) not null default 0,
  mode text not null check (mode in ('normal', 'reverse')) default 'normal',
  reverse_started_at date,
  reverse_first_sell_done boolean not null default false,
  compounding_type text not null check (compounding_type in ('simple', 'compound')) default 'compound',
  is_archived boolean not null default false,
  sort_order integer not null default 0,
  started_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists daily_prices (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  trade_date date not null,
  close_price numeric(18, 4) not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, trade_date)
);

create table if not exists market_candles (
  id bigint generated by default as identity primary key,
  symbol text not null check (symbol in ('TQQQ', 'SOXL')),
  trade_date date not null,
  open_price numeric(18, 4) not null,
  high_price numeric(18, 4) not null,
  low_price numeric(18, 4) not null,
  close_price numeric(18, 4) not null,
  adjusted_close numeric(18, 4),
  volume bigint not null default 0,
  fetched_at timestamptz not null default now(),
  unique(symbol, trade_date)
);

create table if not exists ai_chart_analyses (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  symbol text not null check (symbol in ('TQQQ', 'SOXL')),
  model text not null,
  reasoning_effort text not null,
  candle_start date not null,
  candle_end date not null,
  candle_count integer not null check (candle_count >= 60),
  analysis jsonb,
  openai_response_id text,
  status text not null default 'queued' check (status in ('queued', 'in_progress', 'completed', 'failed', 'cancelled', 'incomplete')),
  error_message text,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table ai_chart_analyses add column if not exists status text;
alter table ai_chart_analyses add column if not exists error_message text;
alter table ai_chart_analyses add column if not exists completed_at timestamptz;
alter table ai_chart_analyses alter column analysis drop not null;
update ai_chart_analyses
set status = case when analysis is not null then 'completed' else 'failed' end
where status is null;
update ai_chart_analyses
set completed_at = coalesce(completed_at, created_at)
where status in ('completed', 'failed', 'cancelled', 'incomplete');
alter table ai_chart_analyses alter column status set default 'queued';
alter table ai_chart_analyses alter column status set not null;
alter table ai_chart_analyses drop constraint if exists ai_chart_analyses_status_check;
alter table ai_chart_analyses
  add constraint ai_chart_analyses_status_check
  check (status in ('queued', 'in_progress', 'completed', 'failed', 'cancelled', 'incomplete'));

create table if not exists trade_plans (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  plan_date date not null,
  mode text not null check (mode in ('normal', 'reverse')),
  phase text,
  t_value numeric(18, 10) not null,
  avg_price numeric(18, 4) not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null,
  star_percent numeric(18, 8),
  star_price numeric(18, 4),
  one_unit_budget numeric(18, 4),
  reverse_reference_price numeric(18, 4),
  guidance jsonb not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, plan_date)
);

create table if not exists executions (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  trade_plan_id uuid references trade_plans(id) on delete set null,
  round_id uuid,
  executed_at date not null,
  side text not null check (side in ('buy', 'sell')),
  order_type text not null check (order_type in ('LOC', 'MOC', 'LIMIT', 'MANUAL')),
  quantity integer not null check (quantity > 0),
  avg_execution_price numeric(18, 4) not null,
  total_amount numeric(18, 4) not null,
  t_effect text check (t_effect in ('buy_full', 'buy_half', 'quarter_sell', 'full_sell', 'limit_sell_then_full_buy', 'limit_sell_then_half_buy', 'reverse_buy', 'reverse_sell', 'none')),
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists completed_rounds (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  round_number integer not null,
  symbol text not null check (symbol in ('TQQQ', 'SOXL')),
  split_count integer not null check (split_count in (20, 40)),
  started_at date not null,
  ended_at date not null,
  started_principal numeric(18, 4) not null,
  ending_cash_balance numeric(18, 4) not null,
  profit_amount numeric(18, 4) not null,
  profit_rate numeric(18, 8) not null,
  execution_count integer not null,
  buy_count integer not null,
  sell_count integer not null,
  total_buy_amount numeric(18, 4) not null,
  total_sell_amount numeric(18, 4) not null,
  ending_t_value numeric(18, 10) not null,
  created_at timestamptz not null default now(),
  unique(strategy_id, round_number)
);

-- Keep existing strategy history while normalizing legacy symbols before
-- tightening the supported-symbol constraints.
update strategies
set symbol = 'SOXL',
    updated_at = now()
where symbol not in ('TQQQ', 'SOXL');

update completed_rounds
set symbol = 'SOXL'
where symbol not in ('TQQQ', 'SOXL');

alter table strategies drop constraint if exists strategies_symbol_check;
alter table strategies add constraint strategies_symbol_check check (symbol in ('TQQQ', 'SOXL'));

alter table completed_rounds drop constraint if exists completed_rounds_symbol_check;
alter table completed_rounds add constraint completed_rounds_symbol_check check (symbol in ('TQQQ', 'SOXL'));

alter table market_candles drop constraint if exists market_candles_symbol_check;
alter table market_candles add constraint market_candles_symbol_check check (symbol in ('TQQQ', 'SOXL'));

alter table executions drop constraint if exists executions_t_effect_check;
alter table executions add constraint executions_t_effect_check check (t_effect in ('buy_full', 'buy_half', 'quarter_sell', 'full_sell', 'limit_sell_then_full_buy', 'limit_sell_then_half_buy', 'reverse_buy', 'reverse_sell', 'none'));

alter table executions add column if not exists round_id uuid;
do $$
begin
  alter table executions
    add constraint executions_round_id_fkey
    foreign key (round_id) references completed_rounds(id) on delete set null;
exception
  when duplicate_object then null;
end $$;

create table if not exists strategy_snapshots (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references strategies(id) on delete cascade,
  execution_id uuid,
  snapshot_date date not null,
  principal numeric(18, 4),
  mode text not null,
  cash_balance numeric(18, 4) not null,
  position_qty integer not null,
  avg_price numeric(18, 4) not null,
  t_value numeric(18, 10) not null,
  started_at date,
  reverse_started_at date,
  reverse_first_sell_done boolean,
  note text,
  created_at timestamptz not null default now()
);

alter table strategy_snapshots add column if not exists execution_id uuid;
alter table strategy_snapshots add column if not exists principal numeric(18, 4);
alter table strategy_snapshots add column if not exists started_at date;
alter table strategy_snapshots add column if not exists reverse_started_at date;
alter table strategy_snapshots add column if not exists reverse_first_sell_done boolean;

create unique index if not exists idx_snapshots_execution on strategy_snapshots (execution_id) where execution_id is not null;

create or replace function cancel_latest_execution(p_strategy_id uuid, p_execution_id uuid)
returns void
language plpgsql
set search_path = public
as $$
declare
  v_strategy strategies%rowtype;
  v_execution executions%rowtype;
  v_latest_execution_id uuid;
  v_snapshot strategy_snapshots%rowtype;
  v_round completed_rounds%rowtype;
begin
  select * into v_strategy
  from strategies
  where id = p_strategy_id
  for update;

  if not found then
    raise exception '전략을 찾을 수 없습니다.';
  end if;

  select id into v_latest_execution_id
  from executions
  where strategy_id = p_strategy_id
  order by created_at desc, id desc
  limit 1;

  if v_latest_execution_id is null or v_latest_execution_id <> p_execution_id then
    raise exception '가장 최근에 입력한 체결만 취소할 수 있습니다.';
  end if;

  select * into v_execution
  from executions
  where id = p_execution_id and strategy_id = p_strategy_id
  for update;

  select * into v_snapshot
  from strategy_snapshots
  where execution_id = p_execution_id
  limit 1;

  if not found then
    select * into v_snapshot
    from strategy_snapshots
    where strategy_id = p_strategy_id
      and created_at <= v_execution.created_at
    order by created_at desc, id desc
    limit 1;
  end if;

  if v_snapshot.id is null
     or v_execution.created_at - v_snapshot.created_at > interval '5 minutes' then
    raise exception '체결 직전 상태를 찾을 수 없어 안전하게 취소할 수 없습니다.';
  end if;

  if v_snapshot.mode = 'reverse'
     and v_snapshot.reverse_started_at is null
     and v_strategy.reverse_started_at is null then
    raise exception '기존 리버스 상태의 시작일을 확인할 수 없어 안전하게 자동 취소할 수 없습니다.';
  end if;

  if v_execution.round_id is not null then
    select * into v_round
    from completed_rounds
    where id = v_execution.round_id and strategy_id = p_strategy_id
    for update;

    if not found
       or v_execution.side <> 'sell'
       or v_round.ended_at <> v_execution.executed_at then
      raise exception '라운드 종료 체결 상태를 확인할 수 없습니다.';
    end if;

    delete from completed_rounds where id = v_round.id;
  end if;

  delete from executions where id = v_execution.id;

  update strategies
  set
    principal = coalesce(v_snapshot.principal, v_round.started_principal, v_strategy.principal),
    cash_balance = v_snapshot.cash_balance,
    position_qty = v_snapshot.position_qty,
    avg_price = v_snapshot.avg_price,
    t_value = v_snapshot.t_value,
    mode = v_snapshot.mode,
    reverse_started_at = case
      when v_snapshot.mode = 'normal' then null
      else coalesce(v_snapshot.reverse_started_at, v_strategy.reverse_started_at)
    end,
    reverse_first_sell_done = case
      when v_snapshot.mode = 'normal' then false
      else coalesce(
        v_snapshot.reverse_first_sell_done,
        exists (
          select 1 from executions
          where strategy_id = p_strategy_id
            and round_id is null
            and t_effect = 'reverse_sell'
        )
      )
    end,
    started_at = coalesce(v_snapshot.started_at, v_round.started_at, v_strategy.started_at),
    updated_at = now()
  where id = p_strategy_id;

  delete from strategy_snapshots where id = v_snapshot.id;
end;
$$;

revoke all on function cancel_latest_execution(uuid, uuid) from public;
grant execute on function cancel_latest_execution(uuid, uuid) to service_role;

create index if not exists idx_strategies_active on strategies (is_archived, sort_order, created_at);
create index if not exists idx_daily_prices_strategy_date on daily_prices (strategy_id, trade_date desc);
create index if not exists idx_market_candles_symbol_date on market_candles (symbol, trade_date desc);
create index if not exists idx_ai_chart_analyses_strategy_date on ai_chart_analyses (strategy_id, created_at desc);
create index if not exists idx_ai_chart_analyses_strategy_status on ai_chart_analyses (strategy_id, status, created_at desc);
create unique index if not exists idx_ai_chart_analyses_openai_response on ai_chart_analyses (openai_response_id) where openai_response_id is not null;
create index if not exists idx_trade_plans_strategy_date on trade_plans (strategy_id, plan_date desc);
create index if not exists idx_executions_strategy_date on executions (strategy_id, executed_at desc);
create index if not exists idx_executions_round on executions (round_id, executed_at desc);
create index if not exists idx_snapshots_strategy_date on strategy_snapshots (strategy_id, snapshot_date desc);
create index if not exists idx_completed_rounds_strategy on completed_rounds (strategy_id, round_number desc);

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

alter default privileges in schema public grant all privileges on tables to service_role;
alter default privileges in schema public grant all privileges on sequences to service_role;

notify pgrst, 'reload schema';

begin;

alter table public.strategies add column if not exists is_main boolean not null default false;

create unique index if not exists strategies_one_main on public.strategies (is_main) where is_main;
alter table public.strategies drop constraint if exists strategies_main_active;
alter table public.strategies add constraint strategies_main_active check (not is_main or not is_archived);

update public.strategies set is_main = true
where id = (
  select id from public.strategies where not is_archived
  order by sort_order, created_at, id limit 1
) and not exists (select 1 from public.strategies where is_main);

create or replace function public.assign_first_main_strategy()
returns trigger language plpgsql set search_path = public as $$
begin
  perform pg_advisory_xact_lock(731204901);
  if not new.is_archived and not exists (select 1 from public.strategies where is_main) then
    new.is_main := true;
  end if;
  return new;
end;
$$;

drop trigger if exists strategies_assign_first_main on public.strategies;
create trigger strategies_assign_first_main before insert on public.strategies
for each row execute function public.assign_first_main_strategy();

create or replace function public.protect_main_strategy()
returns trigger language plpgsql set search_path = public as $$
begin
  if old.is_main then
    if tg_op = 'DELETE' then
      raise exception 'MAIN_STRATEGY_PROTECTED';
    elsif new.is_archived then
      raise exception 'MAIN_STRATEGY_PROTECTED';
    end if;
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists strategies_protect_main on public.strategies;
create trigger strategies_protect_main before update or delete on public.strategies
for each row execute function public.protect_main_strategy();

create or replace function public.set_main_strategy(target_id uuid)
returns void language plpgsql set search_path = public as $$
begin
  perform pg_advisory_xact_lock(731204901);
  perform 1 from public.strategies where id = target_id and not is_archived for update;
  if not found then raise exception 'STRATEGY_NOT_ACTIVE'; end if;

  update public.strategies set is_main = false, updated_at = now() where is_main and id <> target_id;
  update public.strategies set is_main = true, updated_at = now() where id = target_id;
end;
$$;

revoke all on function public.assign_first_main_strategy() from public;
revoke all on function public.protect_main_strategy() from public;
revoke all on function public.set_main_strategy(uuid) from public;
grant execute on function public.set_main_strategy(uuid) to service_role;

notify pgrst, 'reload schema';
commit;

begin;
alter table public.strategies add column if not exists version bigint not null default 0;
alter table public.strategy_snapshots add column if not exists after_cash_balance numeric(18,4);
alter table public.strategy_snapshots add column if not exists after_position_qty integer;
alter table public.executions add column if not exists request_id uuid;

create table if not exists public.strategy_write_requests (
  id uuid primary key,
  strategy_id uuid not null references public.strategies(id) on delete cascade,
  input jsonb not null,
  result jsonb not null,
  cancelled boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.strategy_adjustments (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategies(id) on delete cascade,
  effective_date date not null,
  kind text not null check (kind in ('baseline','correction')),
  before_state jsonb not null,
  after_state jsonb not null,
  reason text not null default '',
  created_at timestamptz not null default now()
);
create unique index if not exists strategy_one_baseline on public.strategy_adjustments(strategy_id) where kind='baseline';
create index if not exists strategy_adjustments_date on public.strategy_adjustments(strategy_id,effective_date,created_at);

insert into public.strategy_adjustments(strategy_id,effective_date,kind,before_state,after_state)
select s.id, coalesce((select max(executed_at) from public.executions where strategy_id=s.id), s.started_at),
  'baseline', to_jsonb(s), to_jsonb(s) from public.strategies s
where not exists(select 1 from public.strategy_adjustments a where a.strategy_id=s.id)
  and exists(select 1 from public.executions where strategy_id=s.id)
  and (select id from public.executions where strategy_id=s.id order by executed_at desc,created_at desc,id desc limit 1)
    = (select id from public.executions where strategy_id=s.id order by created_at desc,id desc limit 1);

create or replace function public.bump_strategy_version() returns trigger language plpgsql set search_path=public as $$
begin new.version := old.version + 1; new.updated_at := clock_timestamp(); return new; end;
$$;
drop trigger if exists strategies_version on public.strategies;
create trigger strategies_version before update on public.strategies for each row execute function public.bump_strategy_version();

create or replace function public.commit_strategy_execution(
  p_strategy_id uuid, p_request_id uuid, p_expected_version bigint, p_input jsonb,
  p_executions jsonb, p_snapshots jsonb, p_final jsonb, p_round jsonb, p_result jsonb
) returns jsonb language plpgsql set search_path=public as $$
declare
  s public.strategies%rowtype; saved public.strategy_write_requests%rowtype;
  e jsonb; snap jsonb; eid uuid; rid uuid; trade_date date;
  ordinal integer := 0; stamp timestamptz := clock_timestamp(); last_date date;
begin
  select * into s from public.strategies where id=p_strategy_id for update;
  if not found or s.is_archived then raise exception 'STRATEGY_NOT_ACTIVE'; end if;
  select * into saved from public.strategy_write_requests where id=p_request_id;
  if found then
    if saved.strategy_id<>p_strategy_id or saved.input<>p_input then raise exception 'REQUEST_CONFLICT'; end if;
    if saved.cancelled then raise exception 'REQUEST_CANCELLED'; end if;
    return saved.result;
  end if;
  if s.version<>p_expected_version then raise exception 'STALE_STRATEGY'; end if;
  if jsonb_array_length(p_executions) not between 1 and 2 or jsonb_array_length(p_executions)<>jsonb_array_length(p_snapshots) then
    raise exception 'INVALID_EXECUTION_BATCH';
  end if;
  trade_date := (p_executions->0->>'executed_at')::date;
  select greatest(
    (select max(executed_at) from public.executions where strategy_id=s.id),
    (select max(effective_date) from public.strategy_adjustments where strategy_id=s.id and kind='correction')
  ) into last_date;
  if trade_date < last_date then raise exception 'EXECUTION_DATE_ORDER'; end if;
  if trade_date > (now() at time zone 'America/New_York')::date or extract(isodow from trade_date) in (6,7) then
    raise exception 'INVALID_EXECUTION_DATE';
  end if;
  for e in select value from jsonb_array_elements(p_executions) loop
    if (e->>'executed_at')::date<>trade_date then raise exception 'INVALID_EXECUTION_BATCH'; end if;
    eid := (e->>'id')::uuid; snap := p_snapshots->ordinal;
    insert into public.strategy_snapshots(strategy_id,execution_id,snapshot_date,principal,mode,cash_balance,position_qty,avg_price,t_value,started_at,reverse_started_at,reverse_first_sell_done,note,created_at,after_cash_balance,after_position_qty)
    values(s.id,eid,trade_date,s.principal,s.mode,(snap->>'cash_balance')::numeric,(snap->>'position_qty')::integer,
      (snap->>'avg_price')::numeric,(snap->>'t_value')::numeric,s.started_at,s.reverse_started_at,s.reverse_first_sell_done,
      '체결 입력 전 상태',stamp+ordinal*interval '1 millisecond',(snap->>'after_cash_balance')::numeric,(snap->>'after_position_qty')::integer);
    insert into public.executions(id,strategy_id,executed_at,side,order_type,quantity,avg_execution_price,total_amount,t_effect,memo,created_at,request_id)
    values(eid,s.id,trade_date,e->>'side',e->>'order_type',(e->>'quantity')::integer,(e->>'avg_execution_price')::numeric,
      (e->>'total_amount')::numeric,e->>'t_effect',e->>'memo',stamp+ordinal*interval '1 millisecond',p_request_id);
    ordinal := ordinal+1;
  end loop;
  if p_round is not null and p_round<>'null'::jsonb then
    if (p_final->>'position_qty')::integer<>0 or p_executions->0->>'side'<>'sell' then raise exception 'INVALID_ROUND_CLOSE'; end if;
    insert into public.completed_rounds(strategy_id,round_number,symbol,split_count,started_at,ended_at,started_principal,ending_cash_balance,
      profit_amount,profit_rate,execution_count,buy_count,sell_count,total_buy_amount,total_sell_amount,ending_t_value)
    select s.id,coalesce((select max(round_number) from public.completed_rounds where strategy_id=s.id),0)+1,s.symbol,s.split_count,
      s.started_at,trade_date,s.principal,(p_final->>'cash_balance')::numeric,(p_round->>'profit_amount')::numeric,(p_round->>'profit_rate')::numeric,
      count(*),count(*) filter(where side='buy'),count(*) filter(where side='sell'),
      coalesce(sum(total_amount) filter(where side='buy'),0),coalesce(sum(total_amount) filter(where side='sell'),0),(p_round->>'ending_t_value')::numeric
    from public.executions where strategy_id=s.id and round_id is null and executed_at between s.started_at and trade_date
    returning id into rid;
    update public.executions set round_id=rid where strategy_id=s.id and round_id is null and executed_at between s.started_at and trade_date;
  end if;
  if (p_final->>'cash_balance')::numeric<0 or (p_final->>'position_qty')::integer<0 or (p_final->>'avg_price')::numeric<0 or (p_final->>'t_value')::numeric<0 then
    raise exception 'INVALID_FINAL_STATE';
  end if;
  update public.strategies set principal=(p_final->>'principal')::numeric,cash_balance=(p_final->>'cash_balance')::numeric,
    position_qty=(p_final->>'position_qty')::integer,avg_price=(p_final->>'avg_price')::numeric,t_value=(p_final->>'t_value')::numeric,
    mode=p_final->>'mode',reverse_first_sell_done=(p_final->>'reverse_first_sell_done')::boolean,
    reverse_started_at=(p_final->>'reverse_started_at')::date,started_at=(p_final->>'started_at')::date where id=s.id;
  insert into public.strategy_write_requests(id,strategy_id,input,result) values(p_request_id,s.id,p_input,p_result);
  return p_result;
end;
$$;

create or replace function public.correct_strategy_state(p_strategy_id uuid,p_expected_version bigint,p_date date,p_state jsonb,p_reason text)
returns void language plpgsql set search_path=public as $$
declare s public.strategies%rowtype; after_row public.strategies%rowtype; last_date date;
begin
  select * into s from public.strategies where id=p_strategy_id for update;
  if not found or s.is_archived then raise exception 'STRATEGY_NOT_ACTIVE'; end if;
  if s.version<>p_expected_version then raise exception 'STALE_STRATEGY'; end if;
  select greatest((select max(executed_at) from public.executions where strategy_id=s.id),
    (select max(effective_date) from public.strategy_adjustments where strategy_id=s.id)) into last_date;
  if p_date is null or p_date<last_date or p_date>(now() at time zone 'Asia/Seoul')::date then raise exception 'CORRECTION_DATE_ORDER'; end if;
  if (p_state->>'principal')::numeric<=0 or (p_state->>'cash_balance')::numeric<0 or (p_state->>'position_qty')::integer<0
    or (p_state->>'avg_price')::numeric<0 or (p_state->>'t_value')::numeric<0 then raise exception 'INVALID_FINAL_STATE'; end if;
  if p_state->>'symbol'<>s.symbol and exists(select 1 from public.executions where strategy_id=s.id) then raise exception 'SYMBOL_HAS_HISTORY'; end if;
  update public.strategies set name=p_state->>'name',symbol=p_state->>'symbol',split_count=(p_state->>'split_count')::integer,
    principal=(p_state->>'principal')::numeric,cash_balance=(p_state->>'cash_balance')::numeric,position_qty=(p_state->>'position_qty')::integer,
    avg_price=(p_state->>'avg_price')::numeric,t_value=(p_state->>'t_value')::numeric,mode=p_state->>'mode',
    reverse_started_at=case when p_state->>'mode'='normal' then null when s.mode='normal' then p_date else s.reverse_started_at end,
    reverse_first_sell_done=case when p_state->>'mode'<>s.mode then false else s.reverse_first_sell_done end
    where id=s.id returning * into after_row;
  insert into public.strategy_adjustments(strategy_id,effective_date,kind,before_state,after_state,reason)
    values(s.id,p_date,'correction',to_jsonb(s),to_jsonb(after_row),coalesce(p_reason,''));
end;
$$;

create or replace function public.cancel_latest_execution(p_strategy_id uuid,p_execution_id uuid)
returns void language plpgsql set search_path=public as $$
declare s public.strategies%rowtype; e public.executions%rowtype; snap public.strategy_snapshots%rowtype;
  r public.completed_rounds%rowtype; ids uuid[];
begin
  select * into s from public.strategies where id=p_strategy_id for update;
  if not found or s.is_archived then raise exception 'STRATEGY_NOT_ACTIVE'; end if;
  select * into e from public.executions where strategy_id=s.id order by created_at desc,id desc limit 1;
  if e.id is null or e.id<>p_execution_id then raise exception '가장 최근에 입력한 체결만 취소할 수 있습니다.'; end if;
  if exists(select 1 from public.strategy_adjustments where strategy_id=s.id and kind='correction' and created_at>e.created_at) then
    raise exception '상태 보정 이후에는 이전 체결을 취소할 수 없습니다.';
  end if;
  select array_agg(id order by created_at,id) into ids from public.executions
    where strategy_id=s.id and (id=e.id or (e.request_id is not null and request_id=e.request_id));
  select * into snap from public.strategy_snapshots where execution_id=ids[1] limit 1;
  if snap.id is null then
    select * into snap from public.strategy_snapshots where strategy_id=s.id and created_at<=e.created_at order by created_at desc,id desc limit 1;
  end if;
  if snap.id is null or e.created_at-snap.created_at>interval '5 minutes' then raise exception '체결 직전 상태를 찾을 수 없습니다.'; end if;
  if snap.mode='reverse' and coalesce(snap.reverse_started_at,s.reverse_started_at) is null then raise exception '리버스 시작일을 확인할 수 없습니다.'; end if;
  if e.round_id is not null then
    select * into r from public.completed_rounds where id=e.round_id and strategy_id=s.id for update;
    if r.id is null or e.side<>'sell' or r.ended_at<>e.executed_at then raise exception '라운드 종료 상태를 확인할 수 없습니다.'; end if;
    delete from public.completed_rounds where id=r.id;
  end if;
  delete from public.executions where id=any(ids);
  update public.strategies set principal=coalesce(snap.principal,r.started_principal,s.principal),cash_balance=snap.cash_balance,
    position_qty=snap.position_qty,avg_price=snap.avg_price,t_value=snap.t_value,mode=snap.mode,
    reverse_started_at=case when snap.mode='normal' then null else coalesce(snap.reverse_started_at,s.reverse_started_at) end,
    reverse_first_sell_done=coalesce(snap.reverse_first_sell_done,false),started_at=coalesce(snap.started_at,s.started_at) where id=s.id;
  update public.strategy_adjustments set effective_date=coalesce((select max(executed_at) from public.executions where strategy_id=s.id),snap.started_at,s.started_at),
    before_state=(select to_jsonb(restored) from public.strategies restored where id=s.id),
    after_state=(select to_jsonb(restored) from public.strategies restored where id=s.id)
    where strategy_id=s.id and kind='baseline' and created_at>e.created_at;
  delete from public.strategy_snapshots where execution_id=any(ids) or id=snap.id;
  update public.strategy_write_requests set cancelled=true where id=e.request_id;
end;
$$;

alter table public.strategy_write_requests enable row level security;
alter table public.strategy_adjustments enable row level security;
revoke all on public.strategy_write_requests,public.strategy_adjustments from public,anon,authenticated;
grant all on public.strategy_write_requests,public.strategy_adjustments to service_role;
revoke all on function public.bump_strategy_version() from public;
revoke all on function public.commit_strategy_execution(uuid,uuid,bigint,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb) from public;
revoke all on function public.correct_strategy_state(uuid,bigint,date,jsonb,text) from public;
revoke all on function public.cancel_latest_execution(uuid,uuid) from public;
grant execute on function public.commit_strategy_execution(uuid,uuid,bigint,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb) to service_role;
grant execute on function public.correct_strategy_state(uuid,bigint,date,jsonb,text) to service_role;
grant execute on function public.cancel_latest_execution(uuid,uuid) to service_role;
notify pgrst,'reload schema';
commit;
